export const enum DIRECTIONS {
  JAVASCRIPT = 'JAVASCRIPT',
  TYPESCRIPT = 'TYPESCRIPT',
  CSHARP = 'CSHARP',
  FRONT_END = 'FRONT_END',
  BACK_END = 'BACK_END',
}

export const enum LEVELS {
  JUNIOR = 'JUNIOR',
  MIDDLE = 'MIDDLE',
  SENIOR = 'SENIOR',
  TEAM_LEAD = 'TEAM_LEAD',
}

export const enum SUBJECTS {
  TYPESCRIPT = 'TYPESCRIPT',
  CSHARP = 'CSHARP',
  FRONT_END = 'FRONT_END',
  BACK_END = 'BACK_END',
  DEVOPS = 'DEVOPS',
}
